name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Job triggered by a ${{ github.event_name }} event."

      - run: echo "🐧 Running on ${{ runner.os }} server hosted by GitHub!"

      - run: 'echo "🔎 Branch: ${{ github.ref }} | Repo: ${{ github.repository }}"'

      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: List files in the repository
        run: ls -la ${{ github.workspace }}

      - run: echo "🍏 Job status: ${{ job.status }}"